export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const AUTH_USER = 'AUTH_USER';
export const GET_USER = 'GET_USER';

export const MY_PLAYLIST = 'MY_PLAYLIST';
export const GET_PLAYLIST_BY_ID = 'GET_PLAYLIST';
export const SAVE_PLAYLIST = 'SAVE_PLAYLIST';
export const SEARCH_PLAYLIST = 'SEARCH_PLAYLIST';

export const GET_MUSICS_BY_PLAYLIST_ID = 'GET_MUSICS_BY_PLAYLIST_ID';
export const ADD_MUSIC = 'ADD_MUSIC';
export const CHANGE_MUSIC_ORDER = 'CHANGE_MUSIC_ORDER';